<!-- AUI Framework -->

<div id="page-breadcrumb-wrapper">

    <div id="page-breadcrumb">
        <a href="javascript:;" title="Dashboard">
            <i class="glyph-icon icon-dashboard"></i>
            Dashboard
        </a>
        <a href="javascript:;" title="Elements">
            <i class="glyph-icon icon-laptop"></i>
            Elements
        </a>
        <span class="current">
            Example breadcrumb
        </span>
    </div>

</div>

<div id="page-content">

    <h1>Enter Html Code here</h1>

</div><!-- #page-content -->
</div><!-- #page-main -->
</div><!-- #page-main-wrapper -->
</div><!-- #page-wrapper -->

</body>


