<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>AgileUI</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <!-- Favicons -->

    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/assets/images/icons/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/images/icons/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/images/icons/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/assets/images/icons/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="/assets/images/icons/favicon.png">

    <!--[if lt IE 9]>
    <script src="/assets/js/minified/core/html5shiv.min.js"></script>
    <script src="/assets/js/minified/core/respond.min.js"></script>
    <![endif]-->

    <!-- AgileUI CSS Core -->

    <link rel="stylesheet" type="text/css" href="/assets/css/minified/aui-production.min.css">

    <!-- Theme UI -->

    <link id="layout-theme" rel="stylesheet" type="text/css" href="/assets/themes/minified/agileui/color-schemes/layouts/default.min.css">
    <link id="elements-theme" rel="stylesheet" type="text/css" href="/assets/themes/minified/agileui/color-schemes/elements/default.min.css">

    <!-- AgileUI Responsive -->

    <link rel="stylesheet" type="text/css" href="/assets/themes/minified/agileui/responsive.min.css">

    <!-- AgileUI Animations -->

    <link rel="stylesheet" type="text/css" href="/assets/themes/minified/agileui/animations.min.css">

    <!-- AgileUI JS -->

    <script type="text/javascript" src="/assets/js/minified/aui-production.min.js"></script>
</head>

<body class="fixed-sidebar fixed-header">


<div id="loading" class="ui-front loader ui-widget-overlay bg-white opacity-100">
    <img src="/assets/images/loader-dark.gif" alt="">
</div>
<!--[if lt IE 7]>
<p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
<![endif]-->

<div id="page-wrapper" class="demo-example">

<div id="page-sidebar">
<div id="header-logo">
    <i class="opacity-80">TrendyLk </i> Admin

    <a href="javascript:;" class="tooltip-button" data-placement="bottom" title="Close sidebar" id="close-sidebar">
        <i class="glyph-icon icon-align-justify"></i>
    </a>
    <a href="javascript:;" class="tooltip-button hidden" data-placement="bottom" title="Open sidebar" id="rm-close-sidebar">
        <i class="glyph-icon icon-align-justify"></i>
    </a>
    <a href="javascript:;" class="tooltip-button hidden" title="Navigation Menu" id="responsive-open-menu">
        <i class="glyph-icon icon-align-justify"></i>
    </a>
</div>


<div id="sidebar-menu" class="scrollable-content">
<ul>
<li>
    <a href="index.html" title="Dashboard">
        <i class="glyph-icon icon-dashboard"></i>
        Dashboard
    </a>
</li>
<li>
    <a href="javascript:;" title="Components">
        <i class="glyph-icon icon-code"></i>
        Components
    </a>
    <ul>
        <li>
            <a href="grid.html" title="Grid Layouts">
                <i class="glyph-icon icon-chevron-right"></i>
                Grid Layouts
            </a>
        </li>
        <li>
            <a href="helper_classes.html" title="Helpers">
                <i class="glyph-icon icon-chevron-right"></i>
                Helpers
            </a>
        </li>
        <li>
            <a href="timeline.html" title="Timeline">
                <i class="glyph-icon icon-chevron-right"></i>
                Timeline
            </a>
        </li>
        <li>
            <a href="dashboard_panels.html" title="Dashboard panels">
                <i class="glyph-icon icon-chevron-right"></i>
                Dashboard panels
            </a>
        </li>
        <li>
            <a href="tile_buttons.html" title="Tile buttons">
                <i class="glyph-icon icon-chevron-right"></i>
                Tile buttons
            </a>
        </li>
        <li>
            <a href="social_boxes.html" title="Social boxes">
                <i class="glyph-icon icon-chevron-right"></i>
                Social boxes
            </a>
        </li>
        <li>
            <a href="todo_list.html" title="Todo list">
                <i class="glyph-icon icon-chevron-right"></i>
                Todo list
            </a>
        </li>
        <li>
            <a href="chat.html" title="Chat">
                <i class="glyph-icon icon-chevron-right"></i>
                Chat
            </a>
        </li>
        <li>
            <a href="calendar.html" title="Calendar">
                <i class="glyph-icon icon-chevron-right"></i>
                Calendar
            </a>
        </li>
        <li>
            <a href="notifications.html" title="Notifications">
                <i class="glyph-icon icon-chevron-right"></i>
                Notifications
            </a>
        </li>
        <li>
            <a href="messaging.html" title="Messaging">
                <i class="glyph-icon icon-chevron-right"></i>
                Messaging
            </a>
        </li>
        <li>
            <a href="progress_bars.html" title="Progress">
                <i class="glyph-icon icon-chevron-right"></i>
                Progress
            </a>
        </li>
    </ul>
</li>
<li>
    <a href="javascript:;" title="Fixed layout">
        <i class="glyph-icon icon-trello"></i>
        Fixed layout
    </a>
    <ul>
        <li>
            <a class="add-fixed-sidebar" href="javascript:;" title="">
                <i class="glyph-icon icon-chevron-right"></i>
                Static sidebar
            </a>
            <a class="rm-fixed-sidebar hidden" href="javascript:;" title="">
                <i class="glyph-icon icon-chevron-right"></i>
                Fixed sidebar
            </a>
        </li>
        <li>
            <a class="add-fixed-header" href="javascript:;" title="">
                <i class="glyph-icon icon-chevron-right"></i>
                Static header
            </a>
            <a class="rm-fixed-header hidden" href="javascript:;" title="">
                <i class="glyph-icon icon-chevron-right"></i>
                Fixed header
            </a>
        </li>
        <li>
            <a class="add-fixed-footer" href="javascript:;" title="">
                <i class="glyph-icon icon-chevron-right"></i>
                Fixed footer
            </a>
            <a class="rm-fixed-footer hidden" href="javascript:;" title="">
                <i class="glyph-icon icon-chevron-right"></i>
                Static footer
            </a>
        </li>
    </ul>
</li>
<li>
    <a href="javascript:;" title="Pages">
        <i class="glyph-icon icon-folder-open"></i>
        Pages
    </a>
    <ul>
        <li>
            <a href="login.html" title="Login">
                <i class="glyph-icon icon-chevron-right"></i>
                Login example 1
            </a>
        </li>
        <li>
            <a href="login-alt.html" title="Login">
                <i class="glyph-icon icon-chevron-right"></i>
                Login example 2
            </a>
        </li>
    </ul>
</li>
<li>
    <a href="javascript:;" title="Widgets">
        <i class="glyph-icon icon-tags"></i>
        Widgets
        <span class="badge primary-bg radius-all-100">19</span>
    </a>
    <ul>
        <li>
            <a href="tabs.html" title="Tabs">
                <i class="glyph-icon icon-chevron-right"></i>
                Tabs
            </a>
        </li>
        <li>
            <a href="accordions.html" title="Accordions">
                <i class="glyph-icon icon-chevron-right"></i>
                Accordions
            </a>
        </li>
        <li>
            <a href="datepicker.html" title="Datepicker">
                <i class="glyph-icon icon-chevron-right"></i>
                Datepicker
            </a>
        </li>
        <li>
            <a href="timepicker.html" title="Timepicker">
                <i class="glyph-icon icon-chevron-right"></i>
                Timepicker
            </a>
        </li>
        <li>
            <a href="colorpicker.html" title="Colorpicker">
                <i class="glyph-icon icon-chevron-right"></i>
                Colorpicker
            </a>
        </li>
        <li>
            <a href="slider.html" title="Sliders">
                <i class="glyph-icon icon-chevron-right"></i>
                Sliders
            </a>
        </li>
        <li>
            <a href="jgrowl_notifications.html" title="JGrowl Notifications">
                <i class="glyph-icon icon-chevron-right"></i>
                JGrowl Notifications
            </a>
        </li>
        <li>
            <a href="noty_notifications.html" title="Noty Notifications">
                <i class="glyph-icon icon-chevron-right"></i>
                Noty Notifications
            </a>
        </li>
        <li>
            <a href="modal_windows.html" title="Modal Windows">
                <i class="glyph-icon icon-chevron-right"></i>
                Modal Windows
            </a>
        </li>
        <li>
            <a href="tooltips.html" title="Tooltips">
                <i class="glyph-icon icon-chevron-right"></i>
                Tooltips
            </a>
        </li>
        <li>
            <a href="popovers.html" title="Popovers">
                <i class="glyph-icon icon-chevron-right"></i>
                Popovers
            </a>
        </li>
        <li>
            <a href="sortable.html" title="Sortable Elements">
                <i class="glyph-icon icon-chevron-right"></i>
                Sortable Elements
            </a>
        </li>
        <li>
            <a href="dropdown_menus.html" title="Dropdown Menus">
                <i class="glyph-icon icon-chevron-right"></i>
                Dropdown Menus
            </a>
        </li>
    </ul>
</li>
<li>
    <a href="javascript:;" title="Elements">
        <i class="glyph-icon icon-laptop"></i>
        Elements
    </a>
    <ul>
        <li>
            <a href="content_boxes.html" title="Content Boxes">
                <i class="glyph-icon icon-chevron-right"></i>
                Content Boxes
            </a>
        </li>
        <li>
            <a href="response_messages.html" title="Response Messages">
                <i class="glyph-icon icon-chevron-right"></i>
                Response Messages
            </a>
        </li>
        <li>
            <a href="information_boxes.html" title="Information boxes">
                <i class="glyph-icon icon-chevron-right"></i>
                Information boxes
            </a>
        </li>
        <li>
            <a href="badges.html" title="Badges &amp; Labels">
                <i class="glyph-icon icon-chevron-right"></i>
                Badges &amp; Labels
            </a>
        </li>
        <li>
            <a href="overlays.html" title="Overlays">
                <i class="glyph-icon icon-chevron-right"></i>
                Overlays
            </a>
        </li>
        <li>
            <a href="navigation_menus.html" title="Navigation Menus">
                <i class="glyph-icon icon-chevron-right"></i>
                Navigation Menus
            </a>
        </li>
        <li>
            <a href="loading_bar.html" title="Loading bars">
                <i class="glyph-icon icon-chevron-right"></i>
                Loading bars
            </a>
        </li>
        <li>
            <a href="icons.html" title="Icons">
                <i class="glyph-icon icon-chevron-right"></i>
                Icons
            </a>
        </li>
        <li>
            <a href="buttons.html" title="Buttons">
                <i class="glyph-icon icon-chevron-right"></i>
                Buttons
            </a>
        </li>
        <li>
            <a href="pagination.html" title="Pagination">
                <i class="glyph-icon icon-chevron-right"></i>
                Pagination
            </a>
        </li>
        <li>
            <a href="progress_bars.html" title="Progress Bars">
                <i class="glyph-icon icon-chevron-right"></i>
                Progress Bars
            </a>
        </li>
        <li>
            <a href="typography.html" title="Typography">
                <i class="glyph-icon icon-chevron-right"></i>
                Typography
            </a>
        </li>
        <li>
            <a href="animations.html" title="Animations">
                <i class="glyph-icon icon-chevron-right"></i>
                Animations
            </a>
        </li>
    </ul>
</li>
<li>
    <a href="javascript:;" title="Data visualization">
        <i class="glyph-icon icon-bar-chart-o"></i>
        Data visualization
    </a>
    <ul>
        <li>
            <a href="charts_xcharts.html" title="xCharts">
                <i class="glyph-icon icon-chevron-right"></i>
                xCharts
            </a>
        </li>
        <li>
            <a href="charts_piegauges.html" title="Pie Gauges">
                <i class="glyph-icon icon-chevron-right"></i>
                Pie Gauges
            </a>
        </li>
        <li>
            <a href="charts_justgage.html" title="JustGage">
                <i class="glyph-icon icon-chevron-right"></i>
                JustGage
            </a>
        </li>
        <li>
            <a href="charts_sparklines.html" title="Sparklines">
                <i class="glyph-icon icon-chevron-right"></i>
                Sparklines
            </a>
        </li>
        <li>
            <a href="charts_morris.html" title="Morris Charts">
                <i class="glyph-icon icon-chevron-right"></i>
                Morris Charts
            </a>
        </li>
    </ul>
</li>
<li>
    <a href="javascript:;" title="Maps">
        <i class="glyph-icon icon-map-marker"></i>
        Maps API
    </a>
    <ul>
        <li>
            <a href="google_maps.html" title="Google Maps">
                <i class="glyph-icon icon-chevron-right"></i>
                Google maps
            </a>
        </li>
        <li>
            <a href="vector_maps.html" title="Vector maps">
                <i class="glyph-icon icon-chevron-right"></i>
                Vector maps
            </a>
        </li>
    </ul>
</li>
<li>
    <a href="javascript:;" title="Tables">
        <i class="glyph-icon icon-table"></i>
        Tables
    </a>
    <ul>
        <li>
            <a href="tables.html" title="Normal tables">
                <i class="glyph-icon icon-chevron-right"></i>
                Normal tables
            </a>
        </li>
        <li>
            <a href="tables_dynamic.html" title="Dynamic tables">
                <i class="glyph-icon icon-chevron-right"></i>
                Dynamic tables
            </a>
        </li>
    </ul>
</li>
<li>
    <a href="javascript:;" title="Forms">
        <i class="glyph-icon icon-leaf"></i>
        Forms
    </a>
    <ul>
        <li>
            <a href="forms.html" title="Layouts &amp; Elements">
                <i class="glyph-icon icon-chevron-right"></i>
                Layouts &amp; Elements
            </a>
        </li>
        <li>
            <a href="forms_validation.html" title="Forms validation">
                <i class="glyph-icon icon-chevron-right"></i>
                Forms validation
            </a>
        </li>
        <li>
            <a href="forms_masks.html" title="Forms input masks">
                <i class="glyph-icon icon-chevron-right"></i>
                Forms input masks
            </a>
        </li>
        <li>
            <a href="forms_knobs.html" title="Input knobs">
                <i class="glyph-icon icon-chevron-right"></i>
                Input knobs
            </a>
        </li>
        <li>
            <a href="form_wizard.html" title="Form wizard">
                <i class="glyph-icon icon-chevron-right"></i>
                Form wizard
            </a>
        </li>
        <li>
            <a href="forms_inline.html" title="Inline editor">
                <i class="glyph-icon icon-chevron-right"></i>
                Inline editor
            </a>
        </li>
        <li>
            <a href="image_editor.html" title="Image crop">
                <i class="glyph-icon icon-chevron-right"></i>
                Image crop
            </a>
        </li>
        <li>
            <a href="file_upload.html" title="Files uploader">
                <i class="glyph-icon icon-chevron-right"></i>
                Files uploader
            </a>
        </li>
        <li>
            <a href="dropzone_uploader.html" title="Dropzone uploader">
                <i class="glyph-icon icon-chevron-right"></i>
                Dropzone uploader
            </a>
        </li>
    </ul>
</li>
<li>
    <a href="javscript:;" title="Change color scheme">
        <i class="glyph-icon icon-picture-o"></i>
        Change theme
        <span class="badge primary-bg radius-all-100">+6</span>
    </a>

    <ul class="change-layout-theme">
        <li>
            <a href="javascript:;" elements-theme="orange" layout-theme="gray" title="Gray">
                <i class="glyph-icon icon-chevron-right"></i>
                Gray orange
            </a>
        </li>
        <li>
            <a href="javascript:;" elements-theme="blue-dark" layout-theme="gray-light" title="Gray Light">
                <i class="glyph-icon icon-chevron-right"></i>
                Gray light, blue dark
            </a>
        </li>
        <li>
            <a href="javascript:;" elements-theme="bg-blue" layout-theme="gray-light" title="Gray Light">
                <i class="glyph-icon icon-chevron-right"></i>
                Gray, blue light
            </a>
        </li>
        <li>
            <a href="javascript:;" elements-theme="black" layout-theme="gray-light" title="Gray Light">
                <i class="glyph-icon icon-chevron-right"></i>
                Gray black
            </a>
        </li>
        <li>
            <a href="javascript:;" elements-theme="green" layout-theme="white" title="White">
                <i class="glyph-icon icon-chevron-right"></i>
                White green
            </a>
        </li>
        <li>
            <a href="javascript:;" elements-theme="orange" layout-theme="white" title="White">
                <i class="glyph-icon icon-chevron-right"></i>
                White orange
            </a>
        </li>
        <li>
            <a href="javascript:;" elements-theme="blue-light" layout-theme="white" title="White">
                <i class="glyph-icon icon-chevron-right"></i>
                White blue light
            </a>
        </li>
        <li>
            <a href="javascript:;" elements-theme="default" layout-theme="default" title="Default">
                <i class="glyph-icon icon-chevron-right"></i>
                Default
            </a>
        </li>
        <li>
            <a href="javascript:;" elements-theme="black" layout-theme="black" title="Black">
                <i class="glyph-icon icon-chevron-right"></i>
                All black
            </a>
        </li>
    </ul>
</li>
</ul>
<div class="divider mrg5T mobile-hidden"></div>
<div class="text-center mobile-hidden">
    <div class="button-group">
        <a href="javascript:;" class="btn medium ui-state-default tooltip-button" data-placement="top" title="Top tooltip">
            <i class="glyph-icon icon-flag"></i>
        </a>
        <a href="javascript:;" class="btn medium ui-state-default tooltip-button" data-placement="bottom" title="Bottom tooltip">
            <i class="glyph-icon icon-inbox"></i>
        </a>
        <a href="javascript:;" class="btn medium ui-state-default tooltip-button" data-placement="right" title="Right tooltip">
            <i class="glyph-icon icon-hdd-o"></i>
        </a>
    </div>

    <div class="divider"></div>
</div>
</div>

</div><!-- #page-sidebar -->

<div id="page-main">

<div id="page-main-wrapper">

<div id="page-header" class="clearfix">
<div id="page-header-wrapper" class="clearfix">
<div class="top-icon-bar dropdown">
    <a href="javascript:;" title="" class="user-ico clearfix" data-toggle="dropdown">
        <img width="36" src="/assets/images/gravatar.jpg" alt="">
        <span>Horia Simon</span>
        <i class="glyph-icon icon-chevron-down"></i>
    </a>
    <ul class="dropdown-menu float-right">
        <li>
            <span class="badge badge-absolute float-left radius-all-100 mrg5R bg-green tooltip-button" title="" data-original-title="You can add badges even to dropdown menus!">7</span>
            <a href="javascript:;" title="">
                <i class="glyph-icon icon-user mrg5R"></i>
                Account Details
            </a>
        </li>
        <li>
            <a href="javascript:;" title="">
                <i class="glyph-icon icon-cog mrg5R"></i>
                Edit Profile
            </a>
        </li>
        <li>
            <a class="font-orange" href="javascript:;" title="">
                <i class="glyph-icon icon-flag mrg5R"></i>
                Notifications
            </a>
        </li>
        <li>
            <a href="javascript:;" title="">
                <i class="glyph-icon icon-signout font-size-13 mrg5R"></i>
                <span class="font-bold">Logout</span>
            </a>
        </li>
        <li class="divider"></li>
        <li class="dropdown-submenu float-left">
            <a href="javascript:;" data-toggle="dropdown" title="">
                Dropdown menu
            </a>
            <ul class="dropdown-menu">
                <li>
                    <a href="javascript:;" title="">
                        Submenu 1
                    </a>
                </li>
                <li>
                    <a href="javascript:;" title="">
                        Submenu 2
                    </a>
                </li>
                <li class="dropdown-submenu">
                    <a href="javascript:;" title="">
                        Submenu 3
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="javascript:;" title="">
                                Submenu 2-1
                            </a>
                        </li>
                        <li>
                            <a href="javascript:;" title="">
                                Submenu 2-2
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </li>
        <li>
            <a href="javascript:;" title="">
                Another menu item
            </a>
        </li>

    </ul>
</div>


<div id="theme-styling" class="hide">
    <div class="small-box">
        <div class="bg-gray text-transform-upr font-size-12 font-bold font-gray-dark pad10A">Layout Color Schemes:</div>
        <div class="pad10A clearfix change-layout-theme">
            <p class="font-gray-dark font-size-11 pad0B">Click to change the layout color scheme. You can associate different color schemes for layouts and main content elements.</p>
            <div class="divider mrg10T mrg10B"></div>
            <a href="javascript:;" class="choose-theme" elements-theme="default" layout-theme="default" title="Default">
                <span style="background: #37485D;"></span>
            </a>
            <a href="javascript:;" class="choose-theme" elements-theme="black" layout-theme="black" title="Black">
                <span style="background: #333;"></span>
            </a>
            <a href="javascript:;" class="choose-theme" elements-theme="orange" layout-theme="gray" title="Gray">
                <span style="background: #4a4a4a;"></span>
            </a>
            <a href="javascript:;" class="choose-theme" elements-theme="blue-dark" layout-theme="gray-light" title="Gray Light">
                <span style="background: #eee;"></span>
            </a>
            <a href="javascript:;" class="choose-theme" elements-theme="green" layout-theme="white" title="White">
                <span style="background: #fafafa;"></span>
            </a>
        </div>

        <div class="bg-gray text-transform-upr font-size-12 font-bold font-gray-dark pad10A">Elements Color Schemes:</div>
        <div class="pad10A clearfix change-layout-theme">
            <p class="font-gray-dark font-size-11 pad0B">When you select a layout color scheme the elements inherit the styles from it, but you can also choose a different color scheme only for elements.</p>
            <div class="divider mrg10T mrg10B"></div>
            <a href="javascript:;" class="choose-theme" elements-theme="default" layout-theme="" title="Default">
                <span style="background: #37485d;"></span>
            </a>
            <a href="javascript:;" class="choose-theme" elements-theme="black" layout-theme="" title="Black">
                <span style="background: #333;"></span>
            </a>
            <a href="javascript:;" class="choose-theme" elements-theme="blue-light" layout-theme="" title="Blue Light">
                <span style="background: #45b3ff;"></span>
            </a>
            <a href="javascript:;" class="choose-theme" elements-theme="blue-dark" layout-theme="" title="Blue Dark">
                <span style="background: #0068c0;"></span>
            </a>
            <a href="javascript:;" class="choose-theme" elements-theme="orange" layout-theme="" title="Orange">
                <span style="background: #f3491c;"></span>
            </a>
            <a href="javascript:;" class="choose-theme" elements-theme="green" layout-theme="" title="Green">
                <span style="background: #269100;"></span>
            </a>
        </div>
        <div class="pad10A button-pane button-pane-alt text-center">
            <a href="aui_theming.html" class="btn medium bg-black">
                <span class="button-content text-transform-upr font-bold font-size-11">Example button</span>
            </a>
        </div>
    </div>
</div>

</div>
</div>
    <div id="page-breadcrumb-wrapper">

        <div id="page-breadcrumb">
            <a href="javascript:;" title="Dashboard">
                <i class="glyph-icon icon-dashboard"></i>
                Dashboard
            </a>
            <a href="javascript:;" title="Elements">
                <i class="glyph-icon icon-laptop"></i>
                Elements
            </a>
        <span class="current">
            Example breadcrumb
        </span>
        </div>

    </div>

    <div id="page-content">
        <div>
            <?php echo $this->layout()->content; ?>
        </div>
    </div>
</div>
</div>
</div>

</body>


<?php echo $this->layout()->content; ?>