<div class="main">
	<div class="title-box">
		<h2>Log in - Admin</h2>
	</div>
	<div id="twocolumns">
		<div class="registration-box">
			<div class="registration-box-holder">
				<div class="registration-box-frame">
					<ul class="registration-breadcrumbs">
						<li class="step1 active">
							<span><strong>STEP 1:</strong> Log in</span>
						</li>
					</ul>
					<div class="registration-form">
						<form method="post">
							<fieldset>
								<div class="holder">
									<div class="column">

									<?php if (isset($this->errors)): ?>
										<div class="error-section">
											<em><span>Problem </span> with logging in. Please try again below.</em>
										</div>
									<?php endif; ?>

										<div class="row">
											<label for="email">Email:</label>
											<div class="text">
												<input type="text" class="text" name="email" value="" />
											</div>
										</div>

										<div class="row">
											<label for="password">Password:</label>
											<div class="text">
												<input type="password" class="text" name="password" value="" />
											</div>
										</div>

										<div class="row">
												<input type="submit" name="submit" value="Sign in" style="margin-left:170px;" />
										</div>
									</div>

									<div class="column column2">

									</div>
								</div>

							</fieldset>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
